### ISSUE TITLE
문장을 이미지로 에서 '저장' 버튼 클릭시 콘솔창에 에러 출력됨

### ISSUE THREAD

**Issue by gisellevonbingen** [norhu1130/stable-diffusion-webui#2]
이슈를 업스트림에 올려야할지 몰루UI에 올려야할지 몰라서 일단 여기 남깁니다

### 실행환 경
Python 3.10.7 (tags/v3.10.7:6cc6b13, Sep  5 2022, 14:08:36) [MSC v.1933 64 bit (AMD64)]
Git 커밋 해시 : d28ec562ca2b085b6f542ebc1b9740f2afd50c19
GPU : NVIDIA GeForce GTX 1080
Web UI를 시작 중... 매개 변수 : --xformers

### 콘솔 출력
```
Error completing request
Arguments: ('{"prompt": "masterpiece, best quality, short yellow hair, yellow eye, open_mouth, {white} open_jacket, {black} crop  sleeveless, stomach , blue nails, black shorts,  mic, {blue} hairband, {blue} waist belt,", "all_prompts": ["masterpiece, best quality, short yellow hair, yellow eye, open_mouth, {white} open_jacket, {black} crop  sleeveless, stomach , blue nails, black shorts,  mic, {blue} hairband, {blue} waist belt,"], "negative_prompt": "lowres, bad anatomy, bad hands, text, error, missing fingers, extra digit, fewer digits, cropped, worst quality, low quality, normal quality, jpeg artifacts, signature, watermark, username, blurry, artist name,\\nblack belt, yellow jacket, blue shorts, ribbon", "seed": 2190696984, "all_seeds": [2190696984], "subseed": 1463845458, "all_subseeds": [1463845458], "subseed_strength": 0, "width": 512, "height": 768, "sampler_index": 0, "sampler": "Euler", "cfg_scale": 11, "steps": 60, "batch_size": 1, "restore_faces": false, "face_restoration_model": null, "sd_model_hash": "925997e9", "seed_resize_from_w": 0, "seed_resize_from_h": 0, "denoising_strength": null, "extra_generation_params": {}, "index_of_first_image": 0, "infotexts": ["masterpiece, best quality, short yellow hair, yellow eye, open_mouth, {white} open_jacket, {black} crop  sleeveless, stomach , blue nails, black shorts,  mic, {blue} hairband, {blue} waist belt,\\nNegative prompt: lowres, bad anatomy, bad hands, text, error, missing fingers, extra digit, fewer digits, cropped, worst quality, low quality, normal quality, jpeg artifacts, signature, watermark, username, blurry, artist name,\\nblack belt, yellow jacket, blue shorts, ribbon\\nSteps: 60, Sampler: Euler, CFG scale: 11, Seed: 2190696984, Size: 512x768, Model hash: 925997e9, Eta: 0.2, Clip skip: 2"], "styles": ["None", "None"], "job_timestamp": "20221012235251", "clip_skip": 2}', ['data:image/png;base64,iVB-중간생략-'], False, 0) {}
Traceback (most recent call last):
  File "C:\Develop\Workspace\stable-diffusion-webui\molru\modules\ui.py", line 182, in f
    res = list(func(*args, **kwargs))
  File "C:\Develop\Workspace\stable-diffusion-webui\molru\modules\ui.py", line 134, in save_files
    with open(os.path.join(opts.outdir_save, "log.csv"), "a", encoding="utf8", newline='') as file:
FileNotFoundError: [Errno 2] No such file or directory: 'log/images\\log.csv'

Traceback (most recent call last):
  File "C:\Develop\Workspace\stable-diffusion-webui\molru\venv\lib\site-packages\gradio\routes.py", line 275, in run_predict
    output = await app.blocks.process_api(
  File "C:\Develop\Workspace\stable-diffusion-webui\molru\venv\lib\site-packages\gradio\blocks.py", line 789, in process_api
    predictions = self.postprocess_data(fn_index, result["prediction"], state)
  File "C:\Develop\Workspace\stable-diffusion-webui\molru\venv\lib\site-packages\gradio\blocks.py", line 740, in postprocess_data
    if predictions[i] is components._Keywords.FINISHED_ITERATING:
IndexError: tuple index out of range
```

**Comment by gisellevonbingen** [comment]
아, 하위 폴더 생성하니까 해결되었습니다
